### ISSUE TITLE
13263?

### ISSUE THREAD

**Issue by JC3** [sparkfun/Fritzing_Parts#32]
Does anybody have or know where I can find a Fritzing file for 13263 (https://www.sparkfun.com/products/13263)? I really am trying hard to learn the parts editor to make one myself (and if I do I'll add it here) but I am struggling with lack of drawing skills... :(

**Comment by bboyho** [comment]
Hi!

Sorry, I just noticed that this issue was filed. I needed to make a part recently for another product and had to grab some SVG files. I quickly made the part with the eagle2fritzing tool while I was at it.

If you or anyone else still needs the file, it is located in this path => https://github.com/sparkfun/Fritzing_Parts/blob/main/products/13263_sfe_ft231x_breakout.fzpz .
